#----plik znajduje sie w folderze /wordpress ----
services:
services:
  wordpress:
    image: wordpress:latest
    container_name: born_to_be_wild
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content # folder współdzielony z kontenerem zawierający szablony, pluginy, etc.
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini # dodatkowe ustawienia PHP
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
    ports:
      - 8123:80
      - 4321:443
    depends_on:
      - db
    networks:
      - wpsite

  db:
    image: mysql:8
    container_name: blogpn_mysql
    restart: always
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wpdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wpsite

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 3333:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password

networks:
  wpsite: {}

volumes:
  db_data: {}
