---
# tasks file for server
#- name: packages | ensure apt list dir exists
#  become: yes
#  file:
#    path: /var/lib/apt/lists/
#    state: directory
#    mode: 0755

#- name: Update apt cache
#  apt: 
#    update_cache: yes 
#    cache_valid_time: 3600
#  become: true

- name: Install required software
  apt: 
    name: "{{ item }}" 
    state: present
  become: yes
  with_items:
    - apache2
    - mysql-server
   #- php7.2-mysql
   #- php7.2
   #- libapache2-mod-php7.2
   #- python-mysqldb
   
   #- php7.2-mysqlnd
   #- php7.2
   #- libapache2-mod-php
   #- python3-mysqldb #to jes ok
