---
- name: Install WordPress
  hosts: all
  remote_user: ubuntu
  become: true

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Install MySQL
      apt:
        name: mysql-server
        state: present

    - name: Install PHP
      apt:
        name: php
        state: present

    - name: Download and extract WordPress
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: "/var/www/html/"
      notify: Restart Apache

    - name: Set up WordPress configuration
      template:
        src: wp-config.php.j2
        dest: "/var/www/html/wordpress/wp-config.php"

    - name: Restart Apache
      service:
        name: apache2
        state: restarted

